### PR TITLE
Search delay (debounce)

### PR DESCRIPTION
**Pull request by fulopkovacs**
300ms delay after keystroke to improve performance when searching on a page with lots of results to filter.

Addresses https://github.com/Poly-Haven/polyhaven.com/issues/10

### CODE REVIEW

**Comment by fulopkovacs** [comment]
Today's progress ([1fd177e](https://github.com/fulopkovacs/polyhaven.com/commit/1fd177e477aec448badf88bbb1f27533bb6694a8)):
- ✅  a debounced function is executed 300 ms after the user stops typing into the search field (see video)
- :x: the results are not filtered.

The internal state management of the `Grid.tsx` component is kinda messy at first glance. I'll have to sort it out a bit to avoid introducing infinite render cycles with my changes.

https://user-images.githubusercontent.com/43729152/201493097-3fb401d1-ca81-474f-87c7-7ddf8a9adc49.mp4

**Comment by gregzaal** [comment]
Looks pretty good to me!

**Comment by fulopkovacs** [comment]
Finally had some time to continue the work on this PR. The search is functional again (but debounced (300ms))! 🎉  

@gregzaal : I managed to achieve these results without refactoring the `Grid` component, but I'm still conflicted about the way that component handles its internal state. It basically does a lot of unnecessary tasks (like sorting every search hit) every time it is rendered (which is every keystroke). I know that reviewing code is hard, and you have a ton of stuff on your plate already, but I think it would be still nice to fix it. Should I create a new PR for that after this one gets merged or should I commit my changes here?

Updated progress:
 - ✅ a debounced function is executed 300 ms after the user stops typing into the search field
 - ✅ the results are filtered
 

https://user-images.githubusercontent.com/43729152/202853017-6b1ae45d-0c94-45a1-a678-880062bde80e.mp4

Also, there is one issue, that is not new, but still annoying. You can slow down your computer + crash the page, if you do this:
1. type a really long string for the search input field really fast (like: `lfaksjdflkasjdfl;hasdoifuweiofjwehfpoe`)
2. Stop
3. Continue typing

I think this slowdown happens because when the user starts typing again, the input field gets updated very slowly, which means that every update passes the 300ms mark, so each keystroke will cause the search function to be executed, which causes the `Grid` component to rerender (the `props` have changed), etc... Haven't looked into the issue, these are just my first thoughts.

https://user-images.githubusercontent.com/43729152/202854633-2d7accf2-28f8-4f17-a1f3-191c3ee65cd0.mp4


The slowdown is annoying, but I don't think it would occur to users, unless they fall asleep on the keyboard, or let their cats to play on it. 😆  I'd say that this PR is mergeable after the `console.log`-s are removed. What's your opinion?

**Comment by gregzaal** [comment]
Yeah this looks great to me! I tested it out with some reasonable long search terms and didn't have any issues.

**Pull request merged**
