### PR TITLE
Webgl previews

### PR DESCRIPTION
**Pull request by dorianzgraggen**
Here's my shot at issue #24. It's still a WIP, but I figured it would make sense to gather feedback early.

## Screenshots

image

By pressing '5' you can toggle the wireframe overlay on or off.
image

By pressing '2' you can cycle through the maps.
image

(Pressing '1' changes back to the PBR material.)

## Known Issues

 - only works with diffuse, roughness and normal atm
 - doesn't work on textures yet
 - camera position doesn't take the model's size into account
 - some issues when switching between 3D scene and preview images
 - GLTFLoader fetches textures that don't exist
 - no UI elements atm
 - doesn't react to window resizes
 - no loading indication
 - switching between images and 3D scene reinitializes everything in the 3D scene
 - looks weird on 'modular_industrial_pipes_01', 'korean_fire_extinguisher_01' (and a bunch more probably)
 - russian_food_cans_01 doesn't work at all

## Questions

I'm not familiar with react, so two things aren't done very elegantly at the moment:

### Binding
When creating the canvas, I append it to the parent element like this:

``` typescript
const inner_container = document.getElementById(id);
// ...
inner_container.appendChild(renderer.domElement);
```
Is there some react-esque way of doing this? For example passing the HTMLElement of the react component to a function?
(I'm thinking of something like [bind:this in Svelte](https://svelte.dev/docs#bind_element).)

### Running code after a component has been created

How can I run code after the component has been created?

Right now, I'm doing this:
``` typescript
// GLTFViewer.tsx
init(id, gltfFiles);
```

And inside of init, I just use setTimeout:
``` typescript
// scene.ts
setTimeout(setupScene, 0, id);
```

I'm aware of [componentDidMount()](https://reactjs.org/docs/react-component.html#componentdidmount), but I couldn't figure out how to use it.

## Feature Suggestions

Personally, I think it would be nice to also be able to preview the model using a matcap when pressing '3' and the UVs when pressing '4'. (Just like on Sketchfab.) Is that something that would be useful?

### CODE REVIEW

**Comment by dorianzgraggen** [comment]
oops, I accidentally submitted, I'm still editing the PR description.

**Comment by chippieTV** [comment]
hi, for binding have a look at https://reactjs.org/docs/hooks-reference.html#useref

instead of getting DOM elements with vanilla JS, use a reference. React DOM elements aren't really stable so need to be controlled a bit differently.

As for loading on first render/setup, if you are using a function component, useEffect with empty dependency array will trigger on first load. https://reactjs.org/docs/hooks-reference.html#useeffect

something like
```
useEffect(() => {
  // code in here will run once when component is mounted
}, []);
```

If you're using class based components, yes you have to deal with lifecycle stuff, but generally it's easier to think and do it all with function components and hooks.

**Comment by gregzaal** [comment]
Function components are definitely the way to go here, keeps things consistent with the rest of the codebase.

I wonder if [@react-three/fiber](https://www.npmjs.com/package/@react-three/fiber) takes care of the binding and initialization in a more elegant way?

> Personally, I think it would be nice to also be able to preview the model using a matcap when pressing '3' and the UVs when pressing '4'. (Just like on Sketchfab.) Is that something that would be useful?

That's a great idea :) Keyboard shortcuts are cool but I think we'll also need little buttons for these too, but I can probably take care of that later.

**Comment by chippieTV** [comment]
I am using @react-three/fiber so if you want an example of it working with the API (it's messy WIP but works) you can see my submission. https://github.com/Poly-Haven/polyhaven.com/pull/37/files

I work a lot with Mapbox and React, and do the binding there manually so there's nothing really wrong with doing that, for Mapbox at least I definitely prefer having the control (or I'm stubborn) but it was a long journey to stability. I'm not so familiar with Three.js so took the easy way out of letting the library handle the binding and setup for me.

**Comment by gregzaal** [comment]
chippie's PR is 99% complete now so I don't think there's much point in continuing with this one, other than for your own interest of course. Maybe you can add something similar on cgbookcase :)

I really appreciate the effort anyway, thanks for helping out!

**Pull request closed without merging**
